title: GitHub Pages Demo Site
author: Jess
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome site description for my test site.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jess-auth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
